name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  release:
    needs: test
    uses: ./.github/workflows/release.yaml
    permissions:
      id-token: write
      contents: write
    secrets: inherit

  docs:
    needs: test
    uses: ./.github/workflows/docs.yaml
    permissions:
      id-token: write
      pages: write
    secrets: inherit
